### ISSUE TITLE
[Bug]: Accessing `value` of sp-menu-item before render throws an error

### ISSUE THREAD

**Issue by charlessuh** [adobe/spectrum-web-components#3626]
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-menu-item

### Actual behavior

Accessing a MenuItem's value before it has rendered can throw the following error:

```
Uncaught TypeError: Cannot read properties of null (reading 'assignedElements')
    at get itemChildren [as itemChildren] (MenuItem.dev.js:140:32)
    at get itemText [as itemText] (MenuItem.dev.js:128:17)
    at get value [as value] (MenuItem.dev.js:111:32)
```

### How can we reproduce this issue?

1. Go to https://studio.webcomponents.dev/edit/BvbfsRX2m4AMWTsc2zTe/src/index.ts?p=stories

**Comment by hunterloftis** [comment]
I'm throwing a similar error stack when I call `Menu.focus()`. This may be a race where the menu hasn't had a chance to render once and collect its assigned elements before I focus it.

**Comment by hunterloftis** [comment]
A quick test provides more evidence that it might be a race to the first render/update cycle. I changed this:

```ts
    private updateFocus(): void {
        this.activeMenu()?.focus({ preventScroll: true });
    };
```

to this:

```ts
    private async updateFocus(): Promise<void> {
        const menu = this.activeMenu();
        if (menu == null) return;

        await menu.updateComplete;
        menu.focus({ preventScroll: true });
    };
```

...and it resolved the issue.

**Comment by Westbrook** [comment]
Fixed in https://github.com/adobe/spectrum-web-components/pull/3669/files#diff-b9cace30081552e1a2c474c35ae00ff7a5c7abe3d7c6b4722179e06d56d4ceb0R138-R141

**Comment by ettchan618** [comment]
Hey @Westbrook, I tried this in the `webcomponents studio` and it looks like the error is still appearing.

https://studio.webcomponents.dev/edit/fdpCdZN6Khei2agAcWud/src/index.ts?p=stories

**Comment by Westbrook** [comment]
Looks like we addressed a _similar_ context elsewhere, and then erroneously marked this as addressed for it. @najikahalsema is looking into a fix for this, soon!
