### ISSUE TITLE
[Bug]: sp-button with href fires twice

### ISSUE THREAD

**Issue by pwong09** [adobe/spectrum-web-components#5557]
### Code of conduct

- [x] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-button

### Expected behavior

When there is a valid href link, expect the sp-button click to only fire once.

### Actual behavior

The button fires twice - we noticed this in our analytics. Please see example: https://stackblitz.com/edit/vitejs-vite-ovhbrt2h?file=src%2Fmy-element.ts

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

3. Scroll to '....'
4. Check console
5. See error

### Severity

None

### Would you like to track this issue in Jira?

- [x] Yes, please tell me the ticket number!

**Comment by najikahalsema** [comment]
This may be fixed by https://github.com/adobe/spectrum-web-components/pull/5204, which was merged 3 days ago but hasn't been released yet. 
Can you take a look? @pwong09

**Comment by pwong09** [comment]
Thanks @najikahalsema I think that solution above should work - didn't realize it hadn't been published yet!

**Comment by najikahalsema** [comment]
resolved by #5204

**Comment by najikahalsema** [comment]
@pwong09 If the PR ends up not resolving the issue once you've had a chance to test the latest release, feel free to reopen this ticket.

**Comment by pwong09** [comment]
Hi @najikahalsema confirming that the latest release `1.7.0` does not fix the double click issue seen on `sp-button` with `href` attribute. Can you double check that it was released in `1.7.0`? Or is there a newer release I should test on?


`Edit`: I've also updated the stackblitz demo to `1.7.0` for folks' reference
